name: Tourism Project Pipeline

on:
  push:
    branches: [main]

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install huggingface_hub
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import login, HfApi
          import os
          login(token=os.getenv('HF_TOKEN'))
          api = HfApi()
          api.upload_file(path_or_fileobj='data/tourism.csv', path_in_repo='tourism.csv', repo_id='akhilbuilds/tourism-data', repo_type='dataset')
          "

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install pandas scikit-learn huggingface_hub
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import login, HfApi
          import os
          import pandas as pd
          from sklearn.model_selection import train_test_split
          login(token=os.getenv('HF_TOKEN'))
          
          df = pd.read_csv('data/tourism.csv')
          df['Gender']=df['Gender'].replace('Fe Male','Female')
          df.fillna(df.median(numeric_only=True), inplace=True)
          train, test = train_test_split(df, test_size=0.3, random_state=42)
          train.to_csv('train.csv', index=False)
          
          api = HfApi()
          api.upload_file(path_or_fileobj='train.csv', path_in_repo='train.csv', repo_id='akhilbuilds/tourism-data', repo_type='dataset')
          "

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [data-prep]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install huggingface_hub
      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import login, HfApi
          import os
          login(token=os.getenv('HF_TOKEN'))
          api = HfApi()
          for f in ['app.py', 'Dockerfile', 'requirements.txt']:
              api.upload_file(path_or_fileobj=f, path_in_repo=f, repo_id='akhilbuilds/wellness-package-predictor', repo_type='space')
          "
